---

- block:
    - name: Make sure the PostgreSQL schemas are present
      become: true
      become_user: postgres
      community.postgresql.postgresql_schema:
        name: "{{ item.schema }}"
        database: "{{ item.db }}"
        owner: "{{ item.owner }}"
        login_unix_socket: "{{ postgresql_unix_socket_dir }}"
        port: "{{ postgresql_port }}"
        state: present
      ignore_errors: true
      loop: "{{ postgresql_schemas | flatten(1) }}"

    - name: Copy PostgreSQL schemas file to /tmp/ folder
      ansible.builtin.copy:
        src: dump.sql
        dest: /tmp/dump.sql

    - name: "Load SQL dump into PostgreSQL"
      become: true
      become_user: postgres
      shell: export PGPASSWORD={{ patroni_superuser_password }}; psql -p {{ postgresql_port }} -h 127.0.0.1 -U {{ patroni_superuser_username }} -d {{ postgresql_load_dump_database }} < /tmp/dump.sql  
  when: postgresql_schemas is defined and postgresql_schemas | length > 0
  tags: postgresql_schemas

...
