---

- name: Deploy Prometheus PostgreSQL Exporter
  hosts: postgres_cluster
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/main.yml
    - vars/system.yml
  roles:
    - role: prometheus_postgresql_exporter